/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { HelloWorld, HelloWorldInterface } from "../../HelloWorld.sol/HelloWorld.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "content",
        "type": "string"
      }
    ],
    "name": "sayHello",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102258061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063c3a9b1c51461002d575b5f5ffd5b61004760048036038101906100429190610114565b61005d565b60405161005491906101cf565b60405180910390f35b606082828080601f0160208091040260200160405190810160405280939291908181526020018383808284375f81840152601f19601f82011690508083019250505050505050905092915050565b5f5ffd5b5f5ffd5b5f5ffd5b5f5ffd5b5f5ffd5b5f5f83601f8401126100d4576100d36100b3565b5b8235905067ffffffffffffffff8111156100f1576100f06100b7565b5b60208301915083600182028301111561010d5761010c6100bb565b5b9250929050565b5f5f6020838503121561012a576101296100ab565b5b5f83013567ffffffffffffffff811115610147576101466100af565b5b610153858286016100bf565b92509250509250929050565b5f81519050919050565b5f82825260208201905092915050565b8281835e5f83830152505050565b5f601f19601f8301169050919050565b5f6101a18261015f565b6101ab8185610169565b93506101bb818560208601610179565b6101c481610187565b840191505092915050565b5f6020820190508181035f8301526101e78184610197565b90509291505056fea2646970667358221220361ae03cbeb9861bae82b7c224b9baee386278aed8e97bea96d8430f024ff40864736f6c634300081c0033";

  
      type HelloWorldConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: HelloWorldConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class HelloWorld__factory extends ContractFactory {
    
      constructor(...args: HelloWorldConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<HelloWorld & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): HelloWorld__factory {
      return super.connect(runner) as HelloWorld__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): HelloWorldInterface {
      return new Interface(_abi) as HelloWorldInterface;
    }
    
    override attach(address: string | Addressable): HelloWorld {
      return super.attach(address) as HelloWorld;
    }
  static connect(address: string, runner?: ContractRunner | null): HelloWorld {
      return new Contract(address, _abi, runner) as unknown as HelloWorld;
    }
  }

  
  